import type { Metadata } from "next"
import "./globals.css"
import Providers from "./providers"
import Navbar from "@/components/Navbar"

export const metadata: Metadata = {
	title: "ABHA",
	description: "Generated by create next app"
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className="w-full min-h-screen h-full" suppressHydrationWarning>
			<body className="antaliased w-full h-full bg-white flex flex-col">
				<Navbar />
				<main className="w-full flex-grow">{children}</main>
			</body>
		</html>
	)
}
